import AppForm from '../app-components/Form/AppForm';

Vue.component('admin-user-form', {
    mixins: [AppForm],
    data: function() {
        return {
            form: {
                tipo:  false ,
                nome:  '' ,
                razao_social:  '' ,
                cpf:  '' ,
                cnpj:  '' ,
                email:  '' ,
                email2:  '' ,
                email3:  '' ,
                telefone:  '' ,
                celular:  '' ,
                logradouro:  '' ,
                numero:  '' ,
                complemento:  '' ,
                bairro:  '' ,
                cidade:  '' ,
                uf:  '' ,
                cep:  '' ,
                vencimento:  '' ,
                valor:  '' ,
                ini_contrato:  '' ,
                fim_contrato:  '' ,
                fistel:  '' ,
                is_admin:  false ,
                activated:  false ,
                forbidden:  false ,
                language:  '' ,
                enabled:  false ,
                password:  '' ,
            },
            ufList: [
                {nome: 'Acre', id: 'AC'},
                {nome: 'Alagoas', id: 'AL'},
                {nome: 'Amapá', id: 'AP'},
                {nome: 'Amazonas', id: 'AM'},
                {nome: 'Bahia', id: 'BA'},
                {nome: 'Ceará', id: 'CE'},
                {nome: 'Distrito Federal', id: 'DF'},
                {nome: 'Espírito Santo', id: 'ES'},
                {nome: 'Goiás', id: 'GO'},
                {nome: 'Maranhão', id: 'MA'},
                {nome: 'Mato Grosso', id: 'MT'},
                {nome: 'Mato Grosso do Sul', id: 'MS'},
                {nome: 'Minas Gerais', id: 'MG'},
                {nome: 'Pará', id: 'PA'},
                {nome: 'Paraíba', id: 'PB'},
                {nome: 'Paraná', id: 'PR'},
                {nome: 'Pernambuco', id: 'PE'},
                {nome: 'Piauí', id: 'PI'},
                {nome: 'Rio de Janeiro', id: 'RJ'},
                {nome: 'Rio Grande do Norte', id: 'RN'},
                {nome: 'Rio Grande do Sul', id: 'RS'},
                {nome: 'Rondônia', id: 'RO'},
                {nome: 'Roraima', id: 'RR'},
                {nome: 'Santa Catarina', id: 'SC'},
                {nome: 'São Paulo', id: 'SP'},
                {nome: 'Sergipe', id: 'SE'},
                {nome: 'Tocantins', id: 'TO'},
            ]
        }
    }
});
